// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgownvywqlanmqsjmueh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnb3dudnl3cWxhbm1xc2ptdWVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NjAxMzMsImV4cCI6MjA2NzEzNjEzM30.RWJ5RStQvPUK5TQDXPiHTQhYp_JsT4w5fP6iVm1L_54";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});